# default: &default
#   adapter: postgresql
#   encoding: unicode
#   database: your_database_name
#   username: postgres
#   password: mysecretpassword # Use the password you specified when starting the PostgreSQL container
#   host: localhost
#   port: 5432 # The port mapping from the container to your host


default: &default
  adapter: postgresql
  encoding: unicode
  database: your_database_name
  username: postgres
  password: mysecretpassword # Use the password you specified when starting the PostgreSQL container
  # host: localhost
  host: 10.0.0.33
  port: 5432 # The port mapping from the container to your host

development:
  <<: *default
  database: pom_reborn_api_development

test:
  <<: *default
  database: pom_reborn_api_test

production:
  <<: *default
  adapter: postgresql
  database: pom-api-prod
  username: pom
  password: <%= ENV['POM_REBORN_API_DATABASE_PASSWORD'] %>
